name: {{ cookiecutter.project_name }}
version: 0.0.0

build-type: Simple

# language: Haskell2010

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - DataKinds
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - PolyKinds
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

ghc-options:
  - -threaded
  - -O2
  - -Wall
  - -Wcompat
  - -Wredundant-constraints
  - -Werror=inaccessible-code
  - -Werror=incomplete-patterns
  - -Werror=missing-fields
  - -Werror=missing-home-modules
  - -Werror=overflowed-literals
  - -Werror=overlapping-patterns

dependencies:
  - name: base
    version: ">= 4.16.2.0 && < 4.17"
    mixin:
      - hiding (Prelude)
  - relude >= 1.1.0.0 && < 1.2


executables:
  {{ cookiecutter.project_name }}:
    main: Main.hs
    source-dirs:
      - src
      - main


tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec >= 2.7.10 && < 3
    build-tools: hspec-discover
