name: build
version: 0.0.0

build-type: Simple

# language: Haskell2010

default-extensions:
  - ApplicativeDo
  - LambdaCase
  - TypeApplications

ghc-options:
  - -threaded
  - -with-rtsopts=-I0
  - -Wall

dependencies:
  - base >= 4.16.2.0
  - directory >= 1.3.6.2
  - shake >= 0.19.6 && < 0.20

executable:
  main: Main.hs
  source-dirs: src
